# -*- coding: utf-8 -*-
"""main2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ahtDB1rGPvXBQk8Fe_Z586tDvAXdHjhm
"""

!pip install fastapi uvicorn pymysql pydantic

from fastapi import FastAPI, HTTPException, Depends
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse
from pydantic import BaseModel
from typing import List, Optional
import pymysql
from pymysql.cursors import DictCursor
from datetime import date, datetime
import os

# =========================
# DATABASE CONFIGURATION
# =========================
DB_CONFIG = {
    "host": "mysql-28fd895c-aucegypt-0c63.b.aivencloud.com",
    "port": 20136,
    "user": "avnadmin",
    "password": "AVNS_0UxQZ4zvk6JGRgu7za5",
    "database": "defaultdb",
    "cursorclass": DictCursor,
    "charset": "utf8mb4"
}

# =========================
# PYDANTIC MODELS
# =========================
class UserRegister(BaseModel):
    email: str
    name: str
    address: str
    birthdate: date
    gender: str
    country: str

class UsageAdd(BaseModel):
    email: str
    identifier: str
    project_name: str
    project_category: str

# =========================
# DATABASE DEPENDENCY
# =========================
def get_db():
    """Create and yield database connection"""
    conn = pymysql.connect(**DB_CONFIG)
    try:
        yield conn
    finally:
        conn.close()

def execute_query(conn, sql: str, params: tuple = None, fetch: bool = True):
    """
    Execute SQL query with parameterized statements to prevent SQL injection

    Args:
        conn: Database connection
        sql: SQL query with %s placeholders
        params: Tuple of parameters (single value needs trailing comma)
        fetch: Whether to fetch results (False for INSERT/UPDATE/DELETE)

    Returns:
        Fetched rows or None
    """
    with conn.cursor() as cursor:
        # Using %s placeholder and params tuple prevents SQL injection
        cursor.execute(sql, params or ())

        if fetch:
            return cursor.fetchall()
        else:
            conn.commit()  # Must commit for INSERT/UPDATE/DELETE
            return None

# =========================
# FASTAPI APP SETUP
# =========================
app = FastAPI(
    title="Data.gov API",
    description="API for accessing and analyzing government datasets",
    version="1.0",
    docs_url="/docs"
)

# Enable CORS for web client
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# =========================
# 1. REGISTER USER
# =========================
@app.post("/users/register", tags=["Users"])
def register_user(user: UserRegister, conn=Depends(get_db)):
    """
    Register a new user in the system

    - **email**: User's email address (unique)
    - **name**: Full name
    - **address**: Physical address
    - **birthdate**: Date of birth (YYYY-MM-DD)
    - **gender**: Male/Female/Other
    - **country**: Country of residence
    """
    # Check if user already exists
    exists = execute_query(
        conn,
        "SELECT email FROM users WHERE email = %s",
        (user.email,)
    )

    if exists:
        raise HTTPException(status_code=400, detail="User already exists")

    # Insert new user
    execute_query(
        conn,
        """
        INSERT INTO users (email, name, address, birthdate, gender, country)
        VALUES (%s, %s, %s, %s, %s, %s)
        """,
        (user.email, user.name, user.address, user.birthdate, user.gender, user.country),
        fetch=False
    )

    return {"message": "User created successfully", "email": user.email}

# =========================
# 2. ADD USER USAGE
# =========================
@app.post("/usage/add", tags=["Usage"])
def add_usage(usage: UsageAdd, conn=Depends(get_db)):
    """
    Record a user's usage of a dataset

    - **email**: User's email address
    - **identifier**: Dataset identifier
    - **project_name**: Name of the project
    - **project_category**: Type of project (analytics/machine learning/field research)
    """
    # Verify user exists
    user = execute_query(
        conn,
        "SELECT email FROM users WHERE email = %s",
        (usage.email,)
    )

    if not user:
        raise HTTPException(status_code=404, detail="User not found")

    # Verify dataset exists
    dataset = execute_query(
        conn,
        "SELECT identifier FROM datasets WHERE identifier = %s",
        (usage.identifier,)
    )

    if not dataset:
        raise HTTPException(status_code=404, detail="Dataset not found")

    # Insert usage record
    execute_query(
        conn,
        """
        INSERT INTO user_records (email, identifier, project_name, project_category)
        VALUES (%s, %s, %s, %s)
        """,
        (usage.email, usage.identifier, usage.project_name, usage.project_category),
        fetch=False
    )

    return {"message": "Usage added successfully"}

# =========================
# 3. VIEW USER USAGE
# =========================
@app.get("/usage/{email}", tags=["Usage"])
def get_user_usage(email: str, conn=Depends(get_db)):
    """
    Get all usage records for a specific user

    - **email**: User's email address
    """
    records = execute_query(
        conn,
        """
        SELECT d.name as dataset_name, ur.project_name, ur.project_category
        FROM user_records ur
        JOIN datasets d ON ur.identifier = d.identifier
        WHERE ur.email = %s
        """,
        (email,)
    )

    if not records:
        return {"message": "No usage records found for this user", "records": []}

    return records

# =========================
# 4. DATASETS BY ORGANIZATION TYPE (FIXED)
# =========================
@app.get("/datasets/organization-type/{org_type}", tags=["Datasets"])
def get_datasets_by_org_type(org_type: str, conn=Depends(get_db)):
    """
    Get datasets filtered by organization type (federal, state, city)

    - **org_type**: Type of organization (federal, state, city)
    """
    # Fixed: Use %% to escape literal % signs in SQL
    return execute_query(
        conn,
        """
        SELECT d.identifier, d.name, d.description, d.category, o.org_name, o.org_type
        FROM datasets d
        JOIN organizations o ON d.org_name = o.org_name
        WHERE LOWER(o.org_type) LIKE CONCAT('%%', %s, '%%')
        LIMIT 50
        """,
        (org_type.lower(),)
    )

# =========================
# 5. TOP 5 ORGANIZATIONS
# =========================
@app.get("/organizations/top", tags=["Organizations"])
def get_top_organizations(conn=Depends(get_db)):
    """
    Get top 5 organizations by number of datasets provided
    """
    top_orgs = execute_query(
        conn,
        """
        SELECT o.org_name, o.org_type, COUNT(d.identifier) as dataset_count
        FROM organizations o
        LEFT JOIN datasets d ON o.org_name = d.org_name
        GROUP BY o.org_name, o.org_type
        ORDER BY dataset_count DESC
        LIMIT 5
        """
    )

    return top_orgs

# =========================
# 6. DATASETS BY FORMAT
# =========================
@app.get("/datasets/format/{format}", tags=["Datasets"])
def get_datasets_by_format(format: str, conn=Depends(get_db)):
    """
    Get datasets available in a specific format (CSV, JSON, PDF, etc.)

    - **format**: File format (csv, json, pdf, xml)
    """
    datasets = execute_query(
        conn,
        """
        SELECT DISTINCT d.identifier, d.name, d.description, d.category, r.source_format
        FROM datasets d
        JOIN resources r ON d.identifier = r.identifier
        WHERE LOWER(r.source_format) = %s
        LIMIT 50
        """,
        (format.lower(),)
    )

    return datasets

# =========================
# 7. DATASETS BY TAG
# =========================
@app.get("/datasets/tag/{tag}", tags=["Datasets"])
def get_datasets_by_tag(tag: str, conn=Depends(get_db)):
    """
    Get datasets associated with a specific tag

    - **tag**: Tag name (climate, education, health, etc.)
    """
    datasets = execute_query(
        conn,
        """
        SELECT DISTINCT d.identifier, d.name, d.description, d.category,
               GROUP_CONCAT(DISTINCT t.tag_name) as tags
        FROM datasets d
        JOIN tags t ON d.identifier = t.identifier
        WHERE LOWER(t.tag_name) = %s
        GROUP BY d.identifier
        LIMIT 50
        """,
        (tag.lower(),)
    )

    return datasets

# =========================
# 8. DISTRIBUTION STATISTICS (FIXED)
# =========================
@app.get("/stats/distribution", tags=["Statistics"])
def get_distribution_stats(conn=Depends(get_db)):
    """
    Get comprehensive statistics about dataset distribution by:
    - Organization
    - Topic/Category
    - Format
    - Organization Type
    """
    stats = {}

    # By organization
    stats["by_organization"] = execute_query(
        conn,
        """
        SELECT o.org_name, o.org_type, COUNT(d.identifier) as count
        FROM organizations o
        LEFT JOIN datasets d ON o.org_name = d.org_name
        GROUP BY o.org_name, o.org_type
        ORDER BY count DESC
        LIMIT 10
        """
    )

    # By topic/category
    stats["by_topic"] = execute_query(
        conn,
        """
        SELECT category, COUNT(identifier) as count
        FROM datasets
        WHERE category IS NOT NULL AND category != ''
        GROUP BY category
        ORDER BY count DESC
        LIMIT 10
        """
    )

    # By format
    stats["by_format"] = execute_query(
        conn,
        """
        SELECT source_format, COUNT(DISTINCT identifier) as count
        FROM resources
        WHERE source_format IS NOT NULL AND source_format != ''
        GROUP BY source_format
        ORDER BY count DESC
        LIMIT 10
        """
    )

    # By organization type - Fixed: Use %% to escape literal % signs
    stats["by_org_type"] = execute_query(
        conn,
        """
        SELECT
            CASE
                WHEN LOWER(org_type) LIKE '%%federal%%' THEN 'Federal'
                WHEN LOWER(org_type) LIKE '%%state%%' THEN 'State'
                WHEN LOWER(org_type) LIKE '%%city%%' OR LOWER(org_type) LIKE '%%municipal%%' THEN 'City'
                ELSE 'Other'
            END as type_category,
            COUNT(DISTINCT d.identifier) as count
        FROM organizations o
        LEFT JOIN datasets d ON o.org_name = d.org_name
        GROUP BY type_category
        ORDER BY count DESC
        """
    )

    return stats

# =========================
# 9. TOP 5 DATASETS BY USERS
# =========================
@app.get("/datasets/top-usage", tags=["Statistics"])
def get_top_datasets_by_users(conn=Depends(get_db)):
    """
    Get top 5 datasets by number of users using them
    """
    top_datasets = execute_query(
        conn,
        """
        SELECT d.identifier, d.name, d.category,
               COUNT(DISTINCT ur.email) AS user_count,
               COUNT(ur.id) AS total_usage_count
        FROM datasets d
        JOIN user_records ur ON d.identifier = ur.identifier
        GROUP BY d.identifier, d.name, d.category
        ORDER BY user_count DESC
        LIMIT 5
        """
    )

    return top_datasets

# =========================
# 10. USAGE BY PROJECT TYPE
# =========================
@app.get("/stats/usage-by-project", tags=["Statistics"])
def get_usage_by_project_type(conn=Depends(get_db)):
    """
    Get distribution of dataset usage by project type with percentages
    """
    usage_stats = execute_query(
        conn,
        """
        SELECT
            project_category,
            COUNT(*) as count,
            ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM user_records), 1) as percentage
        FROM user_records
        WHERE project_category IS NOT NULL
        GROUP BY project_category
        ORDER BY count DESC
        """
    )

    return usage_stats

# =========================
# 11. TOP 10 TAGS BY PROJECT TYPE
# =========================
@app.get("/stats/tags-by-project", tags=["Statistics"])
def get_tags_by_project_type(conn=Depends(get_db)):
    """
    Get top 10 tags associated with each project type
    """
    # Get distinct project types
    project_types = execute_query(
        conn,
        "SELECT DISTINCT project_category FROM user_records WHERE project_category IS NOT NULL"
    )

    result = []

    for pt in project_types:
        project_type = pt['project_category']
        tags = execute_query(
            conn,
            """
            SELECT t.tag_name, COUNT(*) as usage_count
            FROM tags t
            JOIN user_records ur ON t.identifier = ur.identifier
            WHERE ur.project_category = %s
            GROUP BY t.tag_name
            ORDER BY usage_count DESC
            LIMIT 10
            """,
            (project_type,)
        )

        result.append({
            "project_category": project_type,
            "tags": tags
        })

    return result

# =========================
# HEALTH CHECK
# =========================
@app.get("/health", tags=["System"])
def health_check(conn=Depends(get_db)):
    """
    Check API and database health status
    """
    try:
        # Test database connection
        execute_query(conn, "SELECT 1")
        db_status = "connected"
    except Exception as e:
        db_status = f"error: {str(e)}"

    return {
        "status": "healthy",
        "database": db_status,
        "api_version": "1.0"
    }

# =========================
# ROOT ENDPOINT
# =========================
@app.get("/", tags=["System"])
def root():
    """
    Welcome endpoint with API information
    """
    return {
        "message": "Welcome to Data.gov API",
        "documentation": "/docs",
        "health": "/health",
        "endpoints": {
            "users": {
                "POST /users/register": "Register a new user"
            },
            "usage": {
                "POST /usage/add": "Add dataset usage record",
                "GET /usage/{email}": "Get user's usage history"
            },
            "datasets": {
                "GET /datasets/organization-type/{org_type}": "Get datasets by org type",
                "GET /datasets/format/{format}": "Get datasets by format",
                "GET /datasets/tag/{tag}": "Get datasets by tag",
                "GET /datasets/top-usage": "Get top 5 datasets by usage"
            },
            "organizations": {
                "GET /organizations/top": "Get top 5 organizations"
            },
            "statistics": {
                "GET /stats/distribution": "Get distribution statistics",
                "GET /stats/usage-by-project": "Get usage by project type",
                "GET /stats/tags-by-project": "Get top tags by project type"
            },
            "system": {
                "GET /health": "Health check",
                "GET /docs": "Swagger documentation"
            }
        }
    }
